### ISSUE TITLE
About PRCC dataset.

### ISSUE THREAD

**Issue by AsuradaYuci** [MingkunLishigure/MaskCL#1]
Thank you for your great work. However, PRCC's gallery processing seems a little strange. It is somewhat different from the way used in other papers, such as https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py. Why only one sample is selected for each ID in gallery. Is there any origin for this method of randomly selecting 10 times and taking the average?

**Comment by MingkunLishigure** [comment]
您好，感谢您对我们工作的关注！PRCC的Probe和Gallery的选择问题可以参考PRCC原文[
https://www.isee-ai.cn/~yangqize/main_document.pdf]的5.1中Testing and
Evaluation里面
描述的,是在cameraA中每个ID随机抽取一张图像构成Gallery库，因此我们在构成的过程中进行了随机抽取，这一点在Simple-CCReID里面也是一样的，同时10次的话也是由于PRCC作者提出的“随机抽取下，测试10次结果后取平均值作为最终结果”，如果需要的话您也可以使用Simple-CCreid的代码进行验证，我们曾做过相关测试，结果是一样的。

Chenyang Yu ***@***.***> 于2023年9月12日周二 20:39写道：

**Comment by AsuradaYuci** [comment]
@MingkunLishigure 感谢您的回复，我会尝试做一下相关的实验。

**Comment by AsuradaYuci** [comment]
@MingkunLishigure 你好，我按照 https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py. 重新跑了实验，发现mAP降低了差不多有20个点，我只能跑到mAP=38%。我觉得gallery只有一帧这种setting有点问题。您论文中的结果和正常ReID的指标相比的话有点奇怪，mAP比Rank-1高了超过10个点。不知道您能否解答一下这种情况是否合理呢，谢谢。

**Comment by MingkunLishigure** [comment]
请问您是否已经复现了MaskCL原本的结果呢？

Chenyang Yu ***@***.***> 于2023年9月18日周一 10:19写道：

**Comment by AsuradaYuci** [comment]
![image](https://github.com/MingkunLishigure/MaskCL/assets/37969455/c40b3946-b86f-417c-8032-e41427afdca0)
@MingkunLishigure 按照论文描述的使用SHCP生成mask，我跑了您开源的代码，结果差不多如图所示。与汇报的有一定差距吧。下面是我换测试方法的结果。rank-1有提升，但mAP下降明显。
![image](https://github.com/MingkunLishigure/MaskCL/assets/37969455/93291299-97bc-433f-9240-cc43e8204e3b)

**Comment by MingkunLishigure** [comment]
您好，我们按照
https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py.
重新做了一次测试，发现给您回复细节描述上存在一些问题：
1.
https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py.
 里面虽然设计了随机从gallery在每个身份里面抽取一张图像的代码，但是并没有实际使用，测试阶段还是使用的所有gallery中的图像，在这样的情况下，我们的模型结果为：
[image: WechatIMG625.jpg]
如您所见，确实存在一定的下降（10%）。
2.在
https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py.
 中，当我们使用了里面随机设计抽取的代码，将全部的gallery_set转换为随机抽取后的，代码如图所示：
[image: ***@***.***
那么此时的模型测试结果为：
[image: WechatIMG627.jpg]
可以看到此时结果与我们的报告的结果基本相差不大。



3.关于随机抽取的问题，我们是按照PRCC原文的描述进行设计的：
[image: ***@***.***
[image: ***@***.***
因此尽管Simple-CCReID
<https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py>
使用了全部的数据集进行测试，但是我们还是选择了依照PRCC的原文标准进行。
而且可以发现
https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py.
 里面也设计了类似的抽取代码，但是在测试阶段并没有使用这些随机抽取，原因我们并没有询问过。

4.关于mAP高于rank-1的问题，这是由于随机抽取下这种single-shot造成的。


5.我们的确疏忽了 https://github.com/guxinqian/Simple-CCReID
<https://github.com/guxinqian/Simple-CCReID/blob/main/data/datasets/prcc.py>
里面在PRCC上面的测试问题（是否使用了随机抽取），因此直接拿来对比确实有一些不合理，我们在后续的修改版本里面会对这些问题进行进一步核对和说明。感谢您的指出。

Chenyang Yu ***@***.***> 于2023年9月18日周一 17:06写道：

**Comment by AsuradaYuci** [comment]
@MingkunLishigure 感谢您的回复，但我看不到您发给我的图片。https://github.com/guxinqian/Simple-CCReID/issues/7 在这个链接，CAL的作者给了相应的解释。我觉得您这种设置应该也没什么问题，我会进一步做相关的实验。再次感谢。
