### ISSUE TITLE
关于LTCC数据集实验设置的问题

### ISSUE THREAD

**Issue by ykding666** [MingkunLishigure/MaskCL#3]
您的这篇工作很棒，但是我在发现的时候发现了一些问题，想跟您交流一下

我注意到训练过程中的，只打印的一个测试集的结果，论文中是有两个场景的，（CC），SC/general
我通过源码的阅读，发现数据预处理的时候，test部分的数据只有换衣的部分。
然后我单独写了个推理过程的代码，对PRCC,LTCC不换衣的部分进行测试，PRCC是可以复现出论文的结果的，但是LTCC的general场景，与论文中相差较大，不知道是不是我设置的问题，我设置的LTCC数据集中general的query和gallery如图所示（在你的基础上改的）

![微信截图_20241105110626](https://github.com/user-attachments/assets/9f598cf7-5369-4054-b24b-a0069bc4a366)

**Comment by MingkunLishigure** [comment]
感谢您对我们的工作的关注，您这部分的代码修改是没有问题的。在general情况相下，请问您是否修改了maskcl/evaluation_metrics/ranking.py中的valid  &= ((gallery_ids[indices[i]] != query_ids[i]) | (gallery_clothes[indices[i]] != query_clothes[i]))该类代码，在LTCC和VC等数据集上进行general setting的测试时需要将58、125这两行的代码注释掉。相信这样可以解决您说的问题

**Comment by ykding666** [comment]
感谢您的回复，目前是可以达到一个正常的结果了，跟原论文相差1个点以内。感谢！！
